version: "3.9"
services:
  db:
    container_name: 'db'
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ai_agent
      POSTGRES_USER: deepyes02
      POSTGRES_PASSWORD: yEti-2025-yAk-ai
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
  frontend:
    build: ./frontend
    container_name : frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - db
    volumes:
      - ./frontend:/app
    command: npm run dev
  backend:
    env_file:
      - .env
    build: .
    container_name: 'backend'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
volumes:
  database:
  pgadmin:
